type Query {
  jeans: [Jeans]
  dresses: [Dress]
  sale: [Sale]
}

type Jeans {
  id: Int
  name: String
  size: String
  color: String
}

type Dress {
  id: Int
  name: String
  size: String
  color: String
  price: Float
}

type Sale {
  id: Int
  item: String
  discount: Int
  originalPrice: Float
  discountPrice: Float
}

type Jackets {
  id: Int
  name: String
  size: String
  color: String
  price: Int
}

type Accessories {
   id: Int
  name: String
  brand: String
  price: Int
  color: String
}

type Bags {
  id: Int
  name: String
  brand: String
  color: String
  price: Int
}

# GetAllData query definition
query GetAllData {
  jeans {
    id
    name
    size
    color
  }
  dresses {
    id
    name
    size
    color
    price
  }
  sales {
    id
    item
    discount
    originalPrice
    discountPrice
  }
}
